tap "burntsushi/ripgrep", "https://github.com/BurntSushi/ripgrep.git"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "sambadevi/powerlevel9k"
tap "shopify/shopify"
tap "universal-ctags/universal-ctags"
brew "apr"
brew "openssl"
brew "apr-util"
brew "autoconf"
brew "automake"
brew "bison"
brew "boost"
brew "brew-cask-completion"
brew "ghc"
brew "cabal-install"
brew "libpng"
brew "freetype"
brew "fontconfig"
brew "libffi"
brew "glib"
brew "cloc", args: ["HEAD"]
brew "cmake", args: ["HEAD"]
brew "coreutils", args: ["HEAD"]
brew "libusb", args: ["HEAD"]
brew "dfu-util", args: ["HEAD"]
brew "docbook"
brew "docbook-xsl"
brew "doxygen"
brew "editorconfig", args: ["HEAD"]
brew "fd"
brew "gdbm"
brew "jpeg"
brew "libtiff"
brew "readline", link: true
brew "sqlite"
brew "fontforge"
brew "fzf"
brew "webp", args: ["HEAD"]
brew "gengetopt"
brew "git"
brew "gmp"
brew "libunistring"
brew "libgpg-error"
brew "libgcrypt"
brew "libksba"
brew "gnupg"
brew "graphviz"
brew "haskell-stack"
brew "python"
brew "httpie"
brew "idris"
brew "imagemagick", args: ["HEAD"], link: false
brew "imagemagick@6"
brew "jq"
brew "jruby"
brew "jython"
brew "lz4", args: ["HEAD"]
brew "lzlib"
brew "librdkafka"
brew "kafkacat"
brew "libevent"
brew "libgda"
brew "libgraphqlparser"
brew "libidn2"
brew "libxml2", args: ["HEAD"]
brew "libyaml"
brew "lua"
brew "lua@5.1"
brew "mas"
brew "memcached"
brew "mercurial"
brew "neovim"
brew "node"
brew "openssl@1.1"
brew "perl"
brew "plantuml"
brew "postgresql"
brew "redis"
brew "ruby"
brew "ruby-build", args: ["HEAD"]
brew "ruby-install", args: ["HEAD"]
brew "rust"
brew "selenium-server-standalone"
brew "snappy"
brew "sphinx-doc"
brew "subversion"
brew "task"
brew "tcl-tk"
brew "texinfo"
brew "the_silver_searcher", args: ["HEAD"]
brew "tmux", args: ["HEAD"]
brew "tree"
brew "v8"
brew "watchman", args: ["HEAD"]
brew "wine"
brew "winetricks"
brew "yarn"
brew "zlib"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "burntsushi/ripgrep/ripgrep-bin"
brew "sambadevi/powerlevel9k/powerlevel9k"
brew "shopify/shopify/ejson"
brew "shopify/shopify/libzookeeper"
brew "shopify/shopify/mysql-client"
brew "shopify/shopify/shopify-graphicsmagick", args: ["HEAD"]
brew "shopify/shopify/shopify-imagemagick@6", link: true
brew "shopify/shopify/shopify-ruby"
brew "shopify/shopify/toxiproxy"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "chromedriver"
cask "font-iosevka"
cask "font-source-code-pro"
cask "gitify"
cask "google-cloud-sdk"
cask "java"
cask "mono-mdk"
cask "plex-media-player"
cask "sonarr"
cask "shopify/shopify/phantomjs"
mas "Affinity Photo", id: 824183456
mas "ClamXav", id: 430207028
mas "Evernote", id: 406056744
mas "Keynote", id: 409183694
mas "LimeChat", id: 414030210
mas "Monosnap", id: 540348655
mas "Notability", id: 736189492
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Paprika Recipe Manager 3", id: 1303222628
mas "PCalc", id: 403504866
mas "SketchBook", id: 863486266
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
mas "Todoist", id: 585829637
mas "Wake Up Time", id: 495945638
mas "YubiKey Personalization Tool", id: 638161122
