---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- components/**/test/**/*
- vendor/**/*
- ".bundle/**/*"
require: []
domains: []
reporters:
- rubocop
- require_not_found
plugins: []
max_files: 10000
